# To learn more about the options available and their functionality, please
# visit the config.yml documentation on GitHub:
# https://github.com/cervinakuy/KitPvP/wiki/config.yml

Items:
  Kits:
    Enabled: true
    Name: '&aKit Selector &7(Right Click)'
    Material: CHEST
    Slot: 0
    Menu: true
    Commands: []
  Leave:
    Enabled: false
    Name: '&aReturn to Hub &7(Right Click)'
    Material: WATCH
    Slot: 8
    BungeeCord:
      Server: Hub
      Enabled: true
    Commands: []
Chat:
  Format: '%level% &e%player% &f%message%'
  Enabled: false
Combat:
  HitSound:
    Sound: BLAZE_HIT
    Pitch: 1
    Enabled: true
  ArrowHit:
    Message: '&b%player% &7is on &c%health%&7.'
    Enabled: true
  ArrowReturn:
    ItemName: '&eReturnable Arrow'
    NoSpace: '&cYou must have at least one slot open in your inventory for you to
      receive your arrow for your successful shot.'
    Enabled: true
Kill:
  SoupReward:
    NoSpace: '&c%amount% soups could not be added to your full inventory.'
    Amount: 1
    Delay: 0
    Enabled: true
  Commands: []
Death:
  Title:
    Title: '&c&lYOU DIED!'
    Subtitle: '&7You will respawn in %seconds% seconds.'
    Time: 1
    Message: '&7Respawning...'
  Sound:
    Sound: AMBIENCE_THUNDER
    Pitch: 1
    Enabled: false
  Commands: []
  Messages:
    Player: '&b%victim% &7was killed by &b%killer% &7(&c%killer_health%&7).'
    Shot: '&b%victim% &7was shot by &b%killer% &7(&c%killer_health%&7).'
    Fall: '&b%victim% &7fell to their doom.'
    Void: '&b%victim% &7died from the void.'
    Fire: '&b%victim% &7died from fire.'
    Explosion: '&b%victim% &7blew up.'
    Suicide: '&b%victim% &7killed themselves.'
    Unknown: '&b%victim% &7died.'
    Enabled: true
Respawn:
  Commands: []
PlayerTracker:
  Name: '&aPlayer Tracker'
  Message: '&b&lTarget: &3%nearestplayer% &b&lDistance: &3%distance%'
  NoneOnline: '&cNo Players Online'
  TrackBelowY: 128
  RefreshOnlyWhenHeld: true
Soups:
  Name: '&aRegenerative Soups &7(Right Click)'
  RegenAmount: 6
  RemoveAfterUse: true
  Lore:
  - '&7Use this item to regain health.'
  Sound: EAT
  Pitch: 1
  Enabled: true
TNT:
  Name: '&aThrowable TNT &7(Right Click)'
  Enabled: true
Commands:
  Alias:
    Spawn: false
    Kit: false
    Kits: false
    Stats: false
Storage:
  Type: YAML
  MySQL:
    Host: planetgallium.com
    Database: kitpvp
    Table: kitpvp_userdata
    Port: 3306
    Username: walrus
    Password: supersecretpassword
Arena:
  ClearPotionEffectsOnJoin: true
  ClearInventoryOnJoin: true
  ClearInventoryOnLeave: false
  ClearInventoryOnRespawn: true
  ClearInventoryOnKit: true
  ClearKitOnCommandSpawn: true
  PreventBlockBreaking: true
  PreventBlockPlacing: true
  PreventItemDropping: true
  PreventHunger: true
  PreventItemDurabilityDamage: false
  PreventChestOpen: true
  PreventFallDamage: false
  PreventDeathDrops: true
  KeepWeatherAtSunny: true
  GiveItemsOnClear: true
  GiveItemsOnRespawn: true
  GiveItemsOnJoin: true
  NoKitProtection: true
  FancyDeath: false
  ResetKillStreakOnLeave: true
  ToSpawnOnJoin: true
  DeathParticles: true
  PreventArenaSignUseWithKit: true
Other:
  AutomaticallyAddKitToMenu: true
Spawn:
  Time: 5
  Enabled: false
Arenas:
  world_domination:
    blue:
      World: world_domination
      X: -166
      Y: 81
      Z: -61
      Yaw: -127.65106
      Pitch: 12.749929
PreviewMenuBackArrowCommands:
- 'player: kp menu'
